### ISSUE TITLE
What does the '2' mean here?

### ISSUE THREAD

**Issue by alan-yao** [martinsufiofb/LifeStyle#2]
https://github.com/martinsufiofb/LifeStyle/blob/82a16ca4c411b4b3492b3aa76a9d028593d249ba/app/src/main/java/com/example/lifestyle/MainActivity.java#L29

**Comment by martinsufiofb** [comment]
ViewPager2 is an updated version of the ViewPager library that offers improved functionality and addresses usual ViewPager usage issues.
