### ISSUE TITLE
As discussed offline, let's try to think of better solutions for this to make it scalable. (i.e. think about what would you do if there are 100 positions, and there are 10 places need to find the position's corresponding item),

### ISSUE THREAD

**Issue by alan-yao** [martinsufiofb/LifeStyle#4]
https://github.com/martinsufiofb/LifeStyle/blob/82a16ca4c411b4b3492b3aa76a9d028593d249ba/app/src/main/java/com/example/lifestyle/MainActivity.java#L63-L74

**Comment by alan-yao** [comment]
Similar issue in function setBottomNavigation() and ScreenSlidePageAdapter

**Comment by martinsufiofb** [comment]
Done
