### ISSUE TITLE
If I'm understanding this correctly, you are passing the 'position' as the param to identify which exercise the user chose? Let's use meaningful param instead

### ISSUE THREAD

**Issue by alan-yao** [martinsufiofb/LifeStyle#5]
https://github.com/martinsufiofb/LifeStyle/blob/82a16ca4c411b4b3492b3aa76a9d028593d249ba/app/src/main/java/com/example/lifestyle/ExercisesAdapter.java#L72

**Comment by martinsufiofb** [comment]
done
